[project]
name = "phase3"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "adios2>=2.10.1.100042",
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
]
